name: SyncToS3
on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    
jobs:
 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Send email
        uses: dawidd6/action-send-mail@v4.0.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: mech16g@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Test email from GitHub Actions'
          body: 'This is a test email from GitHub Actions!'
          to: 'mechg16@gmail.com'
   