name: SyncToS3
on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    
jobs:
 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Copy a file from s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 'InstrumentTest/file1.json'
          dest: 's3://jsonbackupbucket/InstrumentTest/file1.json'
