
name: SyncToS3

on:

  push:
    branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/s3-sync 
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.ecsitebucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAR55VLGZVW6S33DAU }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.2oZ0LLsWG3U69RTQBE1jV4C2IznluWoCGQMGYWLA }}
          AWS_REGION: ${{ secrets.us-east-2 }}
          SOURCE_DIR: './public'
