name: SyncToS3
on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    
jobs:
 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: send email
        run: |
            python send_email.py ${{ secrets.EMAIL_USERNAME }} ${{ secrets.EMAIL_PASWORD }} ${{ secrets.ACCOUNT }}
   