name: SyncToS3
on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    
jobs:
 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Send email
        uses: wadeww/send-email-action@master
        with:
          server_address: "smtp.gmail.com"
          port: 465
          username: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: jeyapriya@vthink.co.in
          to: jeyapriya@vthink.co.in
          subject: mail title.
          body: your messages.
   
